export const PRODUCTO_NOMBRE_MAX_LENGTH = 80;
export const PRODUCTO_CATEGORIA_MAX_LENGTH = 60;
export const PRODUCTO_DESCRIPCION_MAX_LENGTH = 300;
export const PRODUCTO_PRECIO_MIN = 0;
export const PRODUCTO_PRECIO_MAX = 99999999.99;
